# prefix to be added to name of the resource
namePrefix: prod-
commonLabels:
  env: prod
# directory contains base yaml
bases:
  - ../../base
# patch strategy
patchesStrategicMerge:
  - configmap.yaml
  - order-api.yaml
  - worker-service.yaml
  - secret.yaml
