apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
type: Opaque
data:
  MASS_TRANSIT_AZURE_SERVICE_BUS: "Endpoint=sb://<SERVICE_BUS_NAME>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<SHARED_ACCESS>"